#!/bin/bash
echo "=========================="
echo "       LLVM Builder"
echo "    by Nakada Tokumei"
echo "=========================="

export SRC=$(pwd)
export CLANG_PREFIX=/usr/lib/llvm-20/bin/
export STAGE1=${SRC}/build_stage1
export STAGE1_HOME=${HOME}/build_stage1
export STAGE2=${SRC}/build_stage2
export SYSROOT=${HOME}/sysroot_m2
export SYSROOT_USER=${SYSROOT}/usr

function build_llvm_stage2() {
    if [[ ! -d ${STAGE2} ]]; then
        mkdir -p ${STAGE2}
    fi

    cd ${STAGE2}

    ${SYSROOT_USER}/bin/cmake -S ${SRC}/llvm -G Ninja               \
        -DCMAKE_C_COMPILER=${STAGE1_HOME}/usr/bin/clang                 \
        -DCMAKE_CXX_COMPILER=${STAGE1_HOME}/usr/bin/clang++             \
        -DCMAKE_INSTALL_PREFIX=${SYSROOT_USER}                          \
        -DM2_SYSROOT=${SYSROOT}                                         \
        -C ${SRC}/clang/cmake/caches/M-2-stage2.cmake
    
    ninja -j8

    ninja install
}

build_llvm_stage2